---
- name: Allow plugin.php cli to be executable
  file:
    path: "{{ dokuwiki_plugin_cli }}"
    mode: "u+x,g+x"

- name: Uninstall plugins marked to uninstall
  command: "{{ dokuwiki_plugin_cli }} extension uninstall {{ item.name | default(item) }}"
  args:
    chdir: "{{ dokuwiki_basedir }}"
  when:
    - item.state is defined
    - item.state == "absent"
  ignore_errors: yes
  with_items: "{{ dokuwiki_plugins }}"

- name: Update all plugins
  command: "{{ dokuwiki_plugin_cli }} extension upgrade"
  args:
    chdir: "{{ dokuwiki_basedir }}"
  when: dokuwiki_upgrade_plugins
  
- name: Install plugins marked not to uninstall
  command: "{{ dokuwiki_plugin_cli }} extension install {{ item.name | default(item) }}"
  args:
    chdir: "{{ dokuwiki_basedir }}"
  when:
    - item.state | default('enabled') != "absent" and not item.source is defined
  ignore_errors: yes
  with_items: "{{ dokuwiki_plugins }}"

- name: Clone git plugins
  git:
    repo: "{{ item.source }}"
    dest: "{{ dokuwiki_basedir }}/lib/plugins/{{ item.name }}"
    force: yes
  when:
    - item.state | default('enabled') != "absent" and item.source is defined and item.source_type == "git"
  loop: "{{ dokuwiki_plugins }}"
 
- name: Disable plugins marked as disabled
  command: "{{ dokuwiki_plugin_cli }} extension disable {{ item.name | default(item) }}"
  args:
    chdir: "{{ dokuwiki_basedir }}"
  when: item.state | default('enabled') == "disabled"
  ignore_errors: yes
  with_items: "{{ dokuwiki_plugins }}"
 
- name: Enable plugins marked as enabled
  command: "{{ dokuwiki_plugin_cli }} extension enable {{ item.name | default(item) }}"
  args:
    chdir: "{{ dokuwiki_basedir }}"
  when: item.state | default('enabled') == "enabled"
  ignore_errors: yes
  with_items: "{{ dokuwiki_plugins }}"

- name: Fix disrupted file permissions
  file:
    path: "{{ item }}"
    owner: "{{ dokuwiki_user }}"
    group: "{{ dokuwiki_group }}"
    mode: "{{ dokuwiki_file_mode }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ dokuwiki_basedir }}"
    - "{{ dokuwiki_datadir }}"
  tags:
    - source
    - files
    - permission
